import type {
  Account,
  Transaction,
  User,
} from "@/types";

export const mockUser: User = { id: "user-demo", name: "모비 사용자" };
export const mockAccounts: Account[] = [
  {
    id: "account-demo-1",
    bankName: "모비은행",
    accountName: "생활비 통장",
    accountAlias: "생활비 통장",
    maskedAccountNumber: "123-****-7890",
    accountType: "DEPOSIT",
    isPrimary: true,
    balance: 2_450_000,
    currency: "KRW",
  },
  {
    id: "account-demo-2",
    bankName: "함께은행",
    accountName: "저축 통장",
    accountAlias: "저축 통장",
    maskedAccountNumber: "987-****-4321",
    accountType: "SAVING",
    isPrimary: false,
    balance: 8_100_000,
    currency: "KRW",
  },
];
export const mockTransactions: Transaction[] = [
  {
    id: "transaction-demo-1",
    accountId: "account-demo-1",
    type: "IN",
    description: "급여",
    amount: 3_000_000,
    balanceAfter: 3_250_000,
    counterpartyName: "모비회사",
    category: "급여",
    occurredAt: "2026-08-12T09:00:00+09:00",
    memo: null,
    source: "OPENBANKING",
  },
  {
    id: "transaction-demo-2",
    accountId: "account-demo-1",
    type: "OUT",
    description: "생활비 결제",
    amount: 120_000,
    balanceAfter: 3_130_000,
    counterpartyName: "모비마트",
    category: "생활비",
    occurredAt: "2026-08-12T12:30:00+09:00",
    memo: null,
    source: "OPENBANKING",
  },
  {
    id: "transaction-demo-3",
    accountId: "account-demo-1",
    type: "OUT",
    description: "등록 수취인에게 이체",
    amount: 680_000,
    balanceAfter: 2_450_000,
    counterpartyName: "김모비",
    category: "이체",
    occurredAt: "2026-08-12T18:20:00+09:00",
    memo: "등록 수취인",
    source: "INTERNAL",
  },
  {
    id: "transaction-demo-4",
    accountId: "account-demo-2",
    type: "IN",
    description: "저축 입금",
    amount: 500_000,
    balanceAfter: 8_100_000,
    counterpartyName: null,
    category: "저축",
    occurredAt: "2026-08-11T10:10:00+09:00",
    memo: null,
    source: "OPENBANKING",
  },
];
